# Generated by Django 6.0.5 on 2026-05-09 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('presence', models.CharField(choices=[('oui', 'Présent(e)'), ('non', 'Absent(e)')], default='oui', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_reponse'],
            },
        ),
        migrations.CreateModel(
            name='Accompagnateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompagnateurs', to='bapteme.invitation')),
            ],
        ),
    ]
