# Generated by Django 5.2.8 on 2026-05-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapteme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompagnateur',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accompagnateur',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='date_reponse',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateur_nom', models.CharField(max_length=200, verbose_name='Nom du donateur')),
                ('donateur_tel', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('type_don', models.CharField(choices=[('argent', 'Argent'), ('cadeau', 'Cadeau'), ('autre', 'Autre')], default='argent', max_length=10)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Montant (FCFA)')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Description')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note interne')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='bapteme.invitation', verbose_name='Invité lié')),
            ],
            options={
                'verbose_name': 'Don / Cadeau',
                'verbose_name_plural': 'Dons / Cadeaux',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
